# General.
language: ruby
cache: bundler

rvm:
  - 2.2.0

# Run before.
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database eureka_testing;' -U postgres

script: bundle exec rspec

# Environmental variables.
# Note: These access keys are not real.
env:
  global:
    - AWS_ACCESS_KEY_ID=''
    - AWS_SECRET_ACCESS_KEY=""
    - S3_BUCKET=dummy-bucket
